#dependabot config for pip

version: 2
updates:
  - directory: "/"
    package-ecosystem: "pip"
    schedule:
      interval: "monthly"
    groups:
      cdk:
        patterns:
          - "aws-cdk*"
